-- local wk = require "which-key"
-- wk.add {
--   {
--     "gd",
--     function()
--       vim.lsp.buf.definition()
--     end,
--     desc = "定义",
--   },
--   {
--     "gi",
--     function()
--       vim.lsp.buf.implementation()
--     end,
--     desc = "实现",
--   },
--   {
--     "gr",
--     function()
--       vim.lsp.buf.references()
--     end,
--     desc = "引用",
--   },
--   {
--     "gt",
--     function()
--       vim.lsp.buf.type_definition()
--     end,
--     desc = "类型定义",
--   },
-- }
